// Command d6-ambient certifies, from scratch, the Kazhdan-Lusztig polynomial
// of the length-15 pair of Table 1 (the D6 terminal b and its sub-element x)
// by the KL recursion on the lower Bruhat ideal of b, in three Coxeter
// models: the ambient groups E7 and E8 (geometric representation, exact
// integer matrices) and the D6 parabolic subgroup generated by the support
// of b.
//
// Ports two programs of the October 2026 review code (in the repository history
// at commit d997526; not in the tree):
//
//	research/claude-review-2026-10-07/verification-code/finite-classification/kl.cpp
//	research/claude-review-2026-10-07/verification-code/structural-proofs/kl_d6.py
//
// From kl.cpp: the ideal is enumerated by subwords of b, ordered by length,
// P_{y,b} is computed for every y of the ideal by the standard recursion with
// the first left descent s of y, and the interval [x,b] and its rank vector
// are read off from the support of P_{x,.}. From kl_d6.py: Gern's signed
// permutation model of D6 (words, descent sets, lengths), the label map
// Gern 1..6 -> E7 1,6,2,3,4,5 under which Gern's w6 and x6 are the table
// words, the Bruhat-order test by the lifting property (used here to cross
// check the ideal and the interval by a second method), and a cross check
// against the root record of results/d6-recurrence-certificate.json.
//
// Usage: d6-ambient [-out results/d6-ambient-certificate.json]
// Reads results/d6-recurrence-certificate.json relative to the working
// directory. The certificate contains no timing, host or path fields.
//
// Imports only the standard library: it shares no code with any other engine.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

// ---------------------------------------------------------------- fatal

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "d6-ambient: FAILED: "+format+"\n", args...)
	os.Exit(1)
}

func require(cond bool, format string, args ...any) {
	if !cond {
		fail(format, args...)
	}
}

// ---------------------------------------------------------------- Coxeter model

type mat [8][8]int8

type model struct {
	name   string
	n      int
	labels []int // ambient node label of each index
	c      [8][8]int
	adj    [8][8]bool
	lenMem map[mat]int
}

// newE builds the E_n diagram in the manuscript numbering: a chain 0-1-...-(n-2)
// with node n-1 attached to node 2.
func newE(name string, n int) *model {
	m := &model{name: name, n: n, lenMem: map[mat]int{}}
	for i := 0; i < n; i++ {
		m.labels = append(m.labels, i)
		m.c[i][i] = 2
	}
	edge := func(i, j int) {
		m.adj[i][j], m.adj[j][i] = true, true
		m.c[i][j], m.c[j][i] = -1, -1
	}
	for i := 0; i+1 <= n-2; i++ {
		edge(i, i+1)
	}
	edge(2, n-1)
	return m
}

// restrict returns the parabolic subgroup on the given ambient nodes (sorted),
// with the induced diagram, re-indexed 0..len-1.
func (m *model) restrict(name string, nodes []int) *model {
	r := &model{name: name, n: len(nodes), lenMem: map[mat]int{}}
	for i, a := range nodes {
		r.labels = append(r.labels, m.labels[a])
		for j, b := range nodes {
			r.c[i][j] = m.c[a][b]
			r.adj[i][j] = m.adj[a][b]
		}
	}
	return r
}

func (m *model) index(label int) int {
	for i, l := range m.labels {
		if l == label {
			return i
		}
	}
	return -1
}

func (m *model) identity() mat {
	var a mat
	for i := 0; i < m.n; i++ {
		a[i][i] = 1
	}
	return a
}

func entry(v int) int8 {
	if v < -100 || v > 100 {
		fail("matrix entry %d out of the guarded range", v)
	}
	return int8(v)
}

func (m *model) rightMul(a *mat, i int) {
	o := a[i]
	for k := 0; k < m.n; k++ {
		a[i][k] = -o[k]
	}
	for j := 0; j < m.n; j++ {
		if m.adj[i][j] {
			for k := 0; k < m.n; k++ {
				a[j][k] = entry(int(a[j][k]) + int(o[k]))
			}
		}
	}
}

func (m *model) leftMul(a *mat, i int) {
	for j := 0; j < m.n; j++ {
		p := 0
		for k := 0; k < m.n; k++ {
			p += int(a[j][k]) * m.c[k][i]
		}
		a[j][i] = entry(int(a[j][i]) - p)
	}
}

func (m *model) neg(v [8]int8) bool {
	nz := false
	for k := 0; k < m.n; k++ {
		if v[k] > 0 {
			return false
		}
		if v[k] < 0 {
			nz = true
		}
	}
	return nz
}

func (m *model) rightDescent(a mat, i int) bool { return m.neg(a[i]) }

// length reduces by right descents; memoised.
func (m *model) length(a mat) int {
	if l, ok := m.lenMem[a]; ok {
		return l
	}
	t, l := a, 0
	for {
		s := -1
		for i := 0; i < m.n; i++ {
			if m.rightDescent(t, i) {
				s = i
				break
			}
		}
		if s < 0 {
			break
		}
		m.rightMul(&t, s)
		l++
		require(l < 1000, "length reduction does not terminate")
	}
	m.lenMem[a] = l
	return l
}

func (m *model) leftDescent(a mat, s int) bool {
	t := a
	m.leftMul(&t, s)
	return m.length(t) < m.length(a)
}

// redword returns a reduced word (rightMul sequence from the identity) of a,
// as in kl_d6.py: strip minimal right descents, then reverse.
func (m *model) redword(a mat) []int {
	var word []int
	t := a
	for {
		s := -1
		for i := 0; i < m.n; i++ {
			if m.rightDescent(t, i) {
				s = i
				break
			}
		}
		if s < 0 {
			break
		}
		m.rightMul(&t, s)
		word = append(word, s)
	}
	for i, j := 0, len(word)-1; i < j; i, j = i+1, j-1 {
		word[i], word[j] = word[j], word[i]
	}
	return word
}

func (m *model) wordToElt(word []int) mat {
	a := m.identity()
	for _, s := range word {
		m.rightMul(&a, s)
	}
	return a
}

// bruhatLE is the lifting-property test of kl_d6.py: for w = s w' with s a
// left descent, x <= w iff (s in L(x) ? sx : x) <= w'.
func (m *model) bruhatLE(x mat, wword []int) bool {
	id := m.identity()
	for _, s := range wword {
		if x == id {
			return true // the identity lies below every element
		}
		if m.leftDescent(x, s) {
			m.leftMul(&x, s)
		}
	}
	return x == id
}

func (m *model) descents(a mat, left bool) []int {
	var out []int
	for i := 0; i < m.n; i++ {
		if left {
			if m.leftDescent(a, i) {
				out = append(out, m.labels[i])
			}
		} else if m.rightDescent(a, i) {
			out = append(out, m.labels[i])
		}
	}
	return out
}

func (m *model) parseWord(w string) []int {
	var out []int
	for _, ch := range w {
		require(ch >= '0' && ch <= '9', "bad letter %q in word %q", ch, w)
		i := m.index(int(ch - '0'))
		require(i >= 0, "letter %c of word %q is not a generator of %s", ch, w, m.name)
		out = append(out, i)
	}
	return out
}

// ---------------------------------------------------------------- polynomials

type poly []int64

const polyBound = int64(1) << 31

func addShift(a poly, b poly, sh int, c int64) poly {
	require(c > -polyBound && c < polyBound, "polynomial coefficient overflow guard (multiplier %d)", c)
	for len(a) < len(b)+sh {
		a = append(a, 0)
	}
	for i, v := range b {
		require(v > -polyBound && v < polyBound, "polynomial coefficient overflow guard (%d)", v)
		a[i+sh] += c * v
		require(a[i+sh] > -(int64(1)<<62) && a[i+sh] < int64(1)<<62, "polynomial accumulation overflow guard")
	}
	return a
}

func trim(a poly) poly {
	for len(a) > 0 && a[len(a)-1] == 0 {
		a = a[:len(a)-1]
	}
	return a
}

func polyText(p poly) string {
	var parts []string
	for i, c := range p {
		if c == 0 {
			continue
		}
		var t string
		switch {
		case i == 0:
			t = fmt.Sprint(c)
		case i == 1:
			t = fmt.Sprintf("%sq", coef(c))
		default:
			t = fmt.Sprintf("%sq^%d", coef(c), i)
		}
		parts = append(parts, t)
	}
	return strings.Join(parts, "+")
}

func coef(c int64) string {
	if c == 1 {
		return ""
	}
	return fmt.Sprint(c)
}

func equalPoly(a, b []int64) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// ---------------------------------------------------------------- KL recursion

type klResult struct {
	ideal          int
	topLength      int
	xLength        int
	pXW            poly
	pEW            poly
	mu             int64
	nonCoverMu     int
	intervalSize   int
	rankVector     []int
	bruhatAgrees   bool
	leftDescW      []int
	rightDescW     []int
	leftDescX      []int
	rightDescX     []int
	xInInterval    bool
	wElt, xElt     mat
	idealByMask    int
	liftingChecked int
}

func (m *model) kl(wword, xword []int) klResult {
	L := len(wword)
	require(L <= 20, "word too long for subword enumeration")
	// lower ideal by subwords of the word, first-seen order
	seen := map[mat]int{}
	var elems []mat
	for mask := 0; mask < 1<<uint(L); mask++ {
		a := m.identity()
		for i := 0; i < L; i++ {
			if mask>>uint(i)&1 == 1 {
				m.rightMul(&a, wword[i])
			}
		}
		if _, ok := seen[a]; !ok {
			seen[a] = len(elems)
			elems = append(elems, a)
		}
	}
	M := len(elems)
	ln := make([]int, M)
	for i, e := range elems {
		ln[i] = m.length(e)
	}
	order := make([]int, M)
	for i := range order {
		order[i] = i
	}
	sort.SliceStable(order, func(a, b int) bool { return ln[order[a]] < ln[order[b]] })
	E := make([]mat, M)
	LEN := make([]int, M)
	for i := 0; i < M; i++ {
		E[i] = elems[order[i]]
		LEN[i] = ln[order[i]]
	}
	idx := make(map[mat]int, M)
	for i := 0; i < M; i++ {
		idx[E[i]] = i
	}
	n := m.n
	leftMulIdx := make([][8]int, M)
	LD := make([][8]bool, M)
	for i := 0; i < M; i++ {
		for s := 0; s < n; s++ {
			t := E[i]
			m.leftMul(&t, s)
			j, ok := idx[t]
			if !ok {
				leftMulIdx[i][s] = -1
			} else {
				leftMulIdx[i][s] = j
				LD[i][s] = LEN[j] < LEN[i]
			}
		}
	}
	P := make([]map[int]poly, M)
	for i := range P {
		P[i] = map[int]poly{}
	}
	P[0][0] = poly{1}
	for y := 1; y < M; y++ {
		s := -1
		for t := 0; t < n; t++ {
			if LD[y][t] {
				s = t
				break
			}
		}
		require(s >= 0, "element %d of the ideal has no left descent", y)
		v := leftMulIdx[y][s]
		type zm struct {
			z int
			m int64
		}
		var zs []zm
		for z, p := range P[v] {
			if !LD[z][s] {
				continue
			}
			d := LEN[v] - LEN[z]
			if d%2 == 0 {
				continue
			}
			k := (d - 1) / 2
			if len(p) > k && p[k] != 0 {
				zs = append(zs, zm{z, p[k]})
			}
		}
		sort.Slice(zs, func(a, b int) bool { return zs[a].z < zs[b].z })
		for x := 0; x < M; x++ {
			if LEN[x] > LEN[y] {
				break
			}
			sx := leftMulIdx[x][s]
			c := 0
			if LD[x][s] {
				c = 1
			}
			var r poly
			if sx >= 0 {
				if p, ok := P[v][sx]; ok {
					r = addShift(r, p, 1-c, 1)
				}
			}
			if p, ok := P[v][x]; ok {
				r = addShift(r, p, c, 1)
			}
			for _, z := range zs {
				if p, ok := P[z.z][x]; ok {
					r = addShift(r, p, (LEN[y]-LEN[z.z])/2, -z.m)
				}
			}
			r = trim(r)
			if len(r) > 0 {
				require(r[0] == 1, "constant term != 1 at y=%d x=%d", y, x)
				P[y][x] = r
			}
		}
	}
	w := m.wordToElt(wword)
	x := m.wordToElt(xword)
	wi, ok := idx[w]
	require(ok, "b is not in its own ideal")
	xi, xok := idx[x]
	res := klResult{ideal: M, topLength: LEN[M-1], wElt: w, xElt: x, xInInterval: xok}
	require(LEN[wi] == LEN[M-1], "b is not the top element of its ideal")
	require(len(P[wi]) == M, "support of P_{.,b} (%d) is not the whole ideal (%d)", len(P[wi]), M)
	res.idealByMask = M
	if pe, ok := P[wi][0]; ok {
		res.pEW = pe
	}
	res.leftDescW = m.descents(w, true)
	res.rightDescW = m.descents(w, false)
	res.leftDescX = m.descents(x, true)
	res.rightDescX = m.descents(x, false)
	if !xok {
		return res
	}
	res.xLength = LEN[xi]
	res.pXW = P[wi][xi]
	d := LEN[wi] - LEN[xi]
	if d%2 == 1 && len(res.pXW) > (d-1)/2 {
		res.mu = res.pXW[(d-1)/2]
	}
	for z, p := range P[wi] {
		dd := LEN[wi] - LEN[z]
		if dd%2 == 1 && dd > 1 {
			k := (dd - 1) / 2
			if len(p) > k && p[k] != 0 {
				res.nonCoverMu++
			}
		}
	}
	// interval [x,b] from the support of P_{x,.}, and by the lifting-property test
	res.rankVector = make([]int, d+1)
	wredword := m.redword(w)
	lift := 0
	res.bruhatAgrees = true
	for y := 0; y < M; y++ {
		if LEN[y] < LEN[xi] {
			continue
		}
		_, inSupport := P[y][xi]
		// y is in the ideal of b by construction; x <= y by the lifting criterion on a reduced word of y
		le := m.bruhatLE(x, m.redword(E[y]))
		if le != inSupport {
			res.bruhatAgrees = false
		}
		if inSupport {
			res.rankVector[LEN[y]-LEN[xi]]++
			res.intervalSize++
		}
		lift++
	}
	// the whole ideal lies below b by the lifting criterion
	for y := 0; y < M; y++ {
		if !m.bruhatLE(E[y], wredword) {
			res.bruhatAgrees = false
		}
		lift++
	}
	res.liftingChecked = lift
	return res
}

// ---------------------------------------------------------------- Gern's D6

const nD = 6

func gernRmul(w [nD]int, i int) [nD]int {
	if i == 1 {
		w[0], w[1] = -w[1], -w[0]
	} else {
		w[i-2], w[i-1] = w[i-1], w[i-2]
	}
	return w
}

func gernWordToPerm(word []int) [nD]int {
	var w [nD]int
	for i := range w {
		w[i] = i + 1
	}
	for _, i := range word {
		w = gernRmul(w, i)
	}
	return w
}

func gernR(w [nD]int) []int {
	ext := func(k int) int {
		if k == 0 {
			return -w[1]
		}
		return w[k-1]
	}
	var out []int
	for i := 1; i <= nD; i++ {
		if ext(i-1) > ext(i) {
			out = append(out, i)
		}
	}
	return out
}

func gernInv(w [nD]int) [nD]int {
	var inv [nD]int
	for pos, val := range w {
		p := pos + 1
		a := val
		if a < 0 {
			a = -a
		}
		if val > 0 {
			inv[a-1] = p
		} else {
			inv[a-1] = -p
		}
	}
	return inv
}

func gernLen(w [nD]int) int {
	c := 0
	for i := 0; i < nD; i++ {
		for j := i + 1; j < nD; j++ {
			if w[i] > w[j] {
				c++
			}
			if -w[i] > w[j] {
				c++
			}
		}
	}
	return c
}

// ---------------------------------------------------------------- certificate

type modelRecord struct {
	Name               string  `json:"model"`
	AmbientRank        int     `json:"ambient_rank"`
	NodeLabels         []int   `json:"node_labels"`
	B                  string  `json:"b"`
	X                  string  `json:"x"`
	BLength            int     `json:"b_length"`
	XLength            int     `json:"x_length"`
	LengthGap          int     `json:"length_gap"`
	IdealSize          int     `json:"ideal_size"`
	IntervalSize       int     `json:"interval_size"`
	IntervalRankVector []int   `json:"interval_rank_vector"`
	BruhatByLifting    bool    `json:"ideal_and_interval_agree_with_lifting_property_test"`
	PXB                []int64 `json:"P_xb"`
	PEB                []int64 `json:"P_eb"`
	Mu                 int64   `json:"mu"`
	NonCoverMuCount    int     `json:"non_cover_x_below_b_with_mu_nonzero"`
	LeftDescentsB      []int   `json:"left_descents_b"`
	RightDescentsB     []int   `json:"right_descents_b"`
	LeftDescentsX      []int   `json:"left_descents_x"`
	RightDescentsX     []int   `json:"right_descents_x"`
}

type gernRecord struct {
	W6Word        []int  `json:"w6_word"`
	X6Word        []int  `json:"x6_word"`
	W6Perm        []int  `json:"w6_signed_permutation"`
	X6Perm        []int  `json:"x6_signed_permutation"`
	W6Right       []int  `json:"w6_right_descents"`
	W6Left        []int  `json:"w6_left_descents"`
	X6Right       []int  `json:"x6_right_descents"`
	X6Left        []int  `json:"x6_left_descents"`
	W6Length      int    `json:"w6_length"`
	X6Length      int    `json:"x6_length"`
	LabelMap      string `json:"label_map_gern_to_E7"`
	MappedEqualsW bool   `json:"mapped_w6_equals_table_terminal_in_E7"`
	MappedEqualsX bool   `json:"mapped_x6_equals_table_x_in_E7"`
}

type d6Cross struct {
	File                 string  `json:"file"`
	RootRecordPolynomial []int64 `json:"root_record_polynomial"`
	Equal                bool    `json:"equals_computed_polynomial"`
	RootElementsAreGern  bool    `json:"root_elements_are_gern_x6_w6_signed_permutations"`
	RootIndices          []int   `json:"root_indices"`
}

type certificate struct {
	Claim      string        `json:"claim"`
	Polynomial []int64       `json:"polynomial"`
	PolyText   string        `json:"polynomial_text"`
	Mu         int64         `json:"mu"`
	LengthGap  int           `json:"length_gap"`
	IdealSize  int           `json:"ideal_size"`
	Interval   int           `json:"interval_size"`
	RankVector []int         `json:"interval_rank_vector"`
	Models     []modelRecord `json:"models"`
	Gern       gernRecord    `json:"gern_model"`
	D6Cert     d6Cross       `json:"d6_recurrence_certificate_cross_check"`
	Status     string        `json:"status"`
}

var (
	expectedPoly   = []int64{1, 6, 11, 6, 1, 1}
	expectedRanks  = []int{1, 12, 55, 140, 248, 339, 360, 287, 162, 59, 12, 1}
	expectedIdeal  = 3184
	expectedIntvl  = 1676
	gernW6Word     = []int{2, 1, 4, 3, 2, 1, 6, 5, 4, 3, 2, 1, 5, 4, 6}
	gernX6Word     = []int{1, 2, 4, 6}
	gernLabelMap   = map[int]int{1: 1, 2: 6, 3: 2, 4: 3, 5: 4, 6: 5}
	gernW6Expected = []int{-1, -6, 3, -4, 5, -2}
	gernX6Expected = []int{-1, -2, 4, 3, 6, 5}
)

func intsOf(p [nD]int) []int { return append([]int(nil), p[:]...) }

func sameInts(a, b []int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func record(m *model, ambientRank int, b, x string) (modelRecord, klResult) {
	bw, xw := m.parseWord(b), m.parseWord(x)
	r := m.kl(bw, xw)
	require(r.xInInterval, "%s: x is not in the ideal of b", m.name)
	rec := modelRecord{
		Name: m.name, AmbientRank: ambientRank, NodeLabels: m.labels, B: b, X: x,
		BLength: r.topLength, XLength: r.xLength, LengthGap: r.topLength - r.xLength,
		IdealSize: r.ideal, IntervalSize: r.intervalSize, IntervalRankVector: r.rankVector,
		BruhatByLifting: r.bruhatAgrees, PXB: r.pXW, PEB: r.pEW, Mu: r.mu,
		NonCoverMuCount: r.nonCoverMu,
		LeftDescentsB:   r.leftDescW, RightDescentsB: r.rightDescW,
		LeftDescentsX: r.leftDescX, RightDescentsX: r.rightDescX,
	}
	// assertions of the contract
	require(len(bw) == 15, "%s: b has length %d as a word", m.name, len(bw))
	require(rec.BLength == 15, "%s: l(b)=%d, expected 15", m.name, rec.BLength)
	require(rec.XLength == 4 && rec.LengthGap == 11, "%s: l(x)=%d gap %d", m.name, rec.XLength, rec.LengthGap)
	require(equalPoly(rec.PXB, expectedPoly), "%s: P_{x,b} = %v, expected %v", m.name, rec.PXB, expectedPoly)
	require(equalPoly(rec.PEB, expectedPoly), "%s: P_{e,b} = %v, expected %v", m.name, rec.PEB, expectedPoly)
	require(rec.Mu == 1, "%s: mu(x,b) = %d, expected 1", m.name, rec.Mu)
	require(rec.IdealSize == expectedIdeal, "%s: ideal size %d, expected %d", m.name, rec.IdealSize, expectedIdeal)
	require(rec.IntervalSize == expectedIntvl, "%s: interval size %d, expected %d", m.name, rec.IntervalSize, expectedIntvl)
	require(sameInts(rec.IntervalRankVector, expectedRanks), "%s: rank vector %v", m.name, rec.IntervalRankVector)
	require(rec.BruhatByLifting, "%s: Bruhat comparisons from lifting and recursion differ", m.name)
	require(rec.NonCoverMuCount == 8, "%s: %d non-cover mu-nonzero pairs, expected 8 (the original's printed value)", m.name, rec.NonCoverMuCount)
	return rec, r
}

func main() {
	out := flag.String("out", "results/d6-ambient-certificate.json", "certificate path")
	d6path := flag.String("d6cert", "results/d6-recurrence-certificate.json", "D6 recurrence certificate (for the root cross check)")
	flag.Parse()

	e7 := newE("E7", 7)
	e8 := newE("E8", 8)
	d6 := e7.restrict("D6", []int{1, 2, 3, 4, 5, 6}) // parabolic of E7 generated by nodes 1..6

	var models []modelRecord
	rec7, r7 := record(e7, 7, "132543621324356", "1356")
	models = append(models, rec7)
	rec8, _ := record(e8, 8, "132543721324357", "1357")
	models = append(models, rec8)
	recD, _ := record(d6, 7, "132543621324356", "1356")
	models = append(models, recD)
	require(e8.n == 8, "E8 model")

	// Gern's D6 and the label map (kl_d6.py)
	gp := gernWordToPerm(gernW6Word)
	gx := gernWordToPerm(gernX6Word)
	g := gernRecord{
		W6Word: gernW6Word, X6Word: gernX6Word,
		W6Perm: intsOf(gp), X6Perm: intsOf(gx),
		W6Right: gernR(gp), W6Left: gernR(gernInv(gp)),
		X6Right: gernR(gx), X6Left: gernR(gernInv(gx)),
		W6Length: gernLen(gp), X6Length: gernLen(gx),
		LabelMap: "1,2,3,4,5,6 -> 1,6,2,3,4,5",
	}
	require(len(gernW6Word) == 15, "Gern w6 word length")
	require(sameInts(g.W6Perm, gernW6Expected), "Gern w6 signed permutation %v", g.W6Perm)
	require(sameInts(g.X6Perm, gernX6Expected), "Gern x6 signed permutation %v", g.X6Perm)
	require(sameInts(g.W6Right, []int{1, 2, 4, 6}) && sameInts(g.W6Left, []int{1, 2, 4, 6}), "Gern w6 descents %v %v", g.W6Right, g.W6Left)
	require(sameInts(g.X6Right, []int{1, 2, 4, 6}) && sameInts(g.X6Left, []int{1, 2, 4, 6}), "Gern x6 descents %v %v", g.X6Right, g.X6Left)
	require(g.W6Length == 15 && g.X6Length == 4, "Gern lengths %d %d", g.W6Length, g.X6Length)
	mapWord := func(word []int) []int {
		var o []int
		for _, s := range word {
			o = append(o, gernLabelMap[s])
		}
		return o
	}
	w6E7 := e7.wordToElt(mapWord(gernW6Word))
	x6E7 := e7.wordToElt(mapWord(gernX6Word))
	g.MappedEqualsW = w6E7 == r7.wElt
	g.MappedEqualsX = x6E7 == r7.xElt
	require(g.MappedEqualsW, "mapped Gern w6 differs from the table terminal in E7")
	require(g.MappedEqualsX, "mapped Gern x6 differs from the table x in E7")
	require(e7.length(r7.wElt) == 15, "table word length in E7")
	require(sameInts(rec7.LeftDescentsB, []int{1, 3, 5, 6}) && sameInts(rec7.RightDescentsB, []int{1, 3, 5, 6}), "E7 descents of b: %v %v", rec7.LeftDescentsB, rec7.RightDescentsB)
	require(sameInts(rec7.LeftDescentsX, []int{1, 3, 5, 6}) && sameInts(rec7.RightDescentsX, []int{1, 3, 5, 6}), "E7 descents of x: %v %v", rec7.LeftDescentsX, rec7.RightDescentsX)

	// cross check with the root record of the D6 recurrence certificate
	cross := crossCheck(*d6path, g)

	cert := certificate{
		Claim: "P_{x,b} = 1+6q+11q^2+6q^3+q^4+q^5 with mu(x,b)=1 for the length-15 pair of Table 1 " +
			"(E7: b=132543621324356, x=1356; E8: b=132543721324357, x=1357), computed by the Kazhdan-Lusztig " +
			"recursion on the lower Bruhat ideal of b (3184 elements) in the geometric representation of E7, of E8 " +
			"and of the D6 parabolic generated by the support of b; the interval [x,b] has 1676 elements.",
		Polynomial: expectedPoly, PolyText: polyText(poly(expectedPoly)), Mu: 1, LengthGap: 11,
		IdealSize: expectedIdeal, Interval: expectedIntvl, RankVector: expectedRanks,
		Models: models, Gern: g, D6Cert: cross, Status: "All assertions passed",
	}
	data, err := json.MarshalIndent(cert, "", "  ")
	if err != nil {
		fail("marshal: %v", err)
	}
	data = append(data, '\n')
	if err := os.WriteFile(*out, data, 0o644); err != nil {
		fail("write %s: %v", *out, err)
	}
	fmt.Printf("d6-ambient: P_{x,b} = %s, mu = 1, ideal %d, interval %d in E7, E8 and D6; wrote %s\n",
		polyText(poly(expectedPoly)), expectedIdeal, expectedIntvl, *out)
}

func crossCheck(path string, g gernRecord) d6Cross {
	f, err := os.Open(path)
	if err != nil {
		fail("cannot read %s: %v", path, err)
	}
	defer f.Close()
	var cert struct {
		Elements [][]int `json:"elements"`
		Root     []int   `json:"root"`
		Records  []struct {
			X          *int    `json:"x"`
			W          *int    `json:"w"`
			Polynomial []int64 `json:"polynomial"`
		} `json:"records"`
	}
	if err := json.NewDecoder(f).Decode(&cert); err != nil {
		fail("cannot parse %s: %v", path, err)
	}
	require(len(cert.Root) == 2, "%s: malformed root", path)
	rx, rw := cert.Root[0], cert.Root[1]
	require(rx >= 0 && rx < len(cert.Elements) && rw >= 0 && rw < len(cert.Elements), "%s: root out of range", path)
	cr := d6Cross{File: path, RootIndices: []int{rx, rw}}
	cr.RootElementsAreGern = sameInts(cert.Elements[rx], g.X6Perm) && sameInts(cert.Elements[rw], g.W6Perm)
	require(cr.RootElementsAreGern, "%s: root elements %v, %v are not Gern's x6, w6", path, cert.Elements[rx], cert.Elements[rw])
	found := 0
	for _, r := range cert.Records {
		if r.X != nil && r.W != nil && *r.X == rx && *r.W == rw {
			found++
			cr.RootRecordPolynomial = r.Polynomial
		}
	}
	require(found == 1, "%s: %d root records (expected exactly 1)", path, found)
	cr.Equal = equalPoly(cr.RootRecordPolynomial, expectedPoly)
	require(cr.Equal, "%s: root record polynomial %v differs from the computed one", path, cr.RootRecordPolynomial)
	return cr
}
