"""Certify I6 is neither a principal lower interval nor a lattice.

Uses the exact lifting/subword Bruhat implementation, not KL polynomials.
Run: python3 research/check_i6_shape.py
"""
from itertools import combinations
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'computations'))
from sparse_kl import SparseCoxeter

g = SparseCoxeter('D', 6)
x = (-1, -2, 4, 3, 6, 5)
w = (-1, -6, 3, -4, 5, -2)
interval = sorted(z for z in g.lower(w) if g.leq(x, z))
rank = g.length(w) - g.length(x)
atoms = [z for z in interval if g.length(z) == g.length(x) + 1]
assert rank == 11 and len(atoms) == 12
# An identity-bottom interval of rank d has <=d atoms: the atoms are
# distinct simple generators occurring in a reduced word of length d.
assert len(atoms) > rank

witness = None
for a, b in combinations(atoms, 2):
    common = sorted((z for z in interval if g.leq(a, z) and g.leq(b, z)),
                    key=lambda z: (g.length(z), z))
    minimal = []
    for z in common:
        if not any(g.leq(t, z) for t in minimal):
            minimal.append(z)
    if len(minimal) > 1:
        # Independently verify every minimality claim over all common bounds.
        for z in minimal:
            assert not any(t != z and g.leq(t, z) for t in common)
        assert all(not g.leq(a0, b0) and not g.leq(b0, a0)
                   for a0, b0 in combinations(minimal, 2))
        witness = dict(atoms=[a, b], minimal_common_upper_bounds=minimal,
                       relative_ranks=[g.length(z)-g.length(x) for z in minimal],
                       all_common_upper_bounds_checked=len(common))
        break
assert witness is not None
data = dict(bottom=x, top=w, interval_size=len(interval), rank=rank,
            atoms=atoms, atom_count=len(atoms),
            principal_lower_obstruction='atom_count > interval_rank',
            non_lattice_witness=witness,
            checks='All interval vertices generated by subwords; membership and comparisons use exact lifting property.')
output = ROOT / 'results' / 'i6-shape-certificate.json'
output.write_text(json.dumps(data, indent=2) + '\n')
print(json.dumps(data, indent=2))
