// Command star-family certifies the Kazhdan-Lusztig polynomial of the star
// family of Coxeter groups (a central generator 0 joined to m commuting
// leaves 1..m) and saves every KL dependency of the affine D4 case.
//
// It ports research/broad_cells/certify_star.py (together with star() and the
// Coxeter class of research/broad_cells/targeted.py) to Go; standard library
// only, no other package of this repository is imported. For each m = 1..8 it
// computes P_{x,w} for x = s_1...s_m and w = s_1...s_m s_0 s_1...s_m by the
// Kazhdan-Lusztig recursion on lower Bruhat ideals in the geometric
// representation (integral matrices stored by columns) and asserts the same
// facts as the original: the polynomial equals sum_k (C(m,k)-C(m,k-1)) q^k up to
// degree m/2, the 4^m forms L 0 R are distinct elements with the stated lengths
// and right descents, |lower ideal| = 4^m + 2^m, |[x,w]| = 3^m + 1, the unique
// eligible bottom is x (m >= 2), w is terminal exactly for m >= 3, the Bruhat
// order on the forms is the product of inclusion orders (m <= 4), and the
// recursion computes the same polynomial for every right descent of w.
// For m = 4 it also writes the full dependency certificate.
//
// Outputs (relative to the repository root, original schemas):
//
//	research/broad_cells/star_family_checks.json            (indent=2, as printed)
//	research/broad_cells/affine_d4_kl_certificate.json      (compact separators)
//
// The summary list is also printed on standard output, as the original did.
//
// Invocation, from the repository root:
//
//	go run -C tools ./cmd/star-family
//
// `go run -C tools` runs the program with tools/ as the working directory, so
// the repository root is found by walking upward from the working directory
// until a directory containing results/ and tools/go.mod is reached (the -root
// flag overrides this).
//
// The record order of the dependency certificate is the order in which the
// original first computed each KL value, which depends on the iteration order
// of Python frozensets of matrices; pyset.go reproduces CPython's hash-table
// layout so that the committed certificate is regenerated byte for byte.
package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "star-family: "+format+"\n", args...)
	os.Exit(1)
}

func check(cond bool, format string, args ...any) {
	if !cond {
		fatalf("assertion failed: "+format, args...)
	}
}

func main() {
	rootFlag := flag.String("root", "", "repository root (default: found by walking up from the working directory)")
	flag.Parse()
	if flag.NArg() != 0 {
		fatalf("unexpected arguments: %v", flag.Args())
	}
	root, err := findRoot(*rootFlag)
	if err != nil {
		fatalf("%v", err)
	}
	var summaries []any
	var certificate []byte
	for m := 1; m <= 8; m++ {
		out, cert := certify(m, m == 4, m <= 4)
		summaries = append(summaries, out)
		if cert != nil {
			certificate = cert
		}
	}
	dir := filepath.Join(root, "research", "broad_cells")
	checks := append(encodeJSON(summaries, true), '\n')
	if err := os.WriteFile(filepath.Join(dir, "affine_d4_kl_certificate.json"), certificate, 0o644); err != nil {
		fatalf("%v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "star_family_checks.json"), checks, 0o644); err != nil {
		fatalf("%v", err)
	}
	os.Stdout.Write(checks)
}

func findRoot(explicit string) (string, error) {
	start := explicit
	if start == "" {
		wd, err := os.Getwd()
		if err != nil {
			return "", err
		}
		start = wd
	}
	start, err := filepath.Abs(start)
	if err != nil {
		return "", err
	}
	if resolved, err := filepath.EvalSymlinks(start); err == nil {
		start = resolved
	}
	if explicit != "" {
		if !isRoot(start) {
			return "", fmt.Errorf("%s is not a repository root (needs results/ and tools/go.mod)", explicit)
		}
		return start, nil
	}
	for dir := start; ; {
		if isRoot(dir) {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("repository root not found: run from the repository root or below it")
		}
		dir = parent
	}
}

func isRoot(dir string) bool {
	if st, err := os.Stat(filepath.Join(dir, "results")); err != nil || !st.IsDir() {
		return false
	}
	st, err := os.Stat(filepath.Join(dir, "tools", "go.mod"))
	return err == nil && st.Mode().IsRegular()
}

func binom(n, k int) int64 {
	if k < 0 || k > n {
		return 0
	}
	r := int64(1)
	for i := 1; i <= k; i++ {
		r = r * int64(n-k+i) / int64(i)
	}
	return r
}

func intPow(b, e int) int {
	r := 1
	for i := 0; i < e; i++ {
		r *= b
	}
	return r
}

func equalPoly(a, b []int64) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func intSet(xs []int) map[int]bool {
	s := map[int]bool{}
	for _, x := range xs {
		s[x] = true
	}
	return s
}

// certify is certify(m, certificate, all_orders) of the original. It returns the
// summary object and, when requested, the encoded dependency certificate.
func certify(m int, certificate, allOrders bool) (object, []byte) {
	g := star(m)
	A := make([]int, m)
	for i := range A {
		A[i] = i + 1
	}
	topWord := append(append(append([]int{}, A...), 0), A...)
	x := g.elt(A)
	w := g.elt(topWord)
	p := g.kl(x, w)
	expected := make([]int64, m/2+1)
	for k := range expected {
		expected[k] = binom(m, k) - binom(m, k-1)
	}
	check(equalPoly(p, expected), "m=%d: polynomial %v != %v", m, p, expected)

	lowerOrder := g.lower(w).order()
	var interval []int32
	inInterval := map[int32]bool{}
	for _, z := range lowerOrder {
		if g.leq(x, z) {
			interval = append(interval, z)
			inInterval[z] = true
		}
	}

	type form struct {
		L, R uint64 // bit masks of leaves
	}
	forms := map[int32]form{}
	var formOrder []int32
	total := intPow(4, m)
	for code := 0; code < total; code++ {
		// product(range(4), repeat=m): the first leaf is the most significant digit.
		var L, R []int
		var lm, rm uint64
		for i := 0; i < m; i++ {
			st := (code >> uint(2*(m-1-i))) & 3
			if st&1 != 0 {
				L = append(L, i+1)
				lm |= 1 << uint(i)
			}
			if st&2 != 0 {
				R = append(R, i+1)
				rm |= 1 << uint(i)
			}
		}
		word := append(append(append([]int{}, L...), 0), R...)
		z := g.elt(word)
		_, dup := forms[z]
		check(!dup, "m=%d: duplicate element for statuses %d", m, code)
		forms[z] = form{lm, rm}
		formOrder = append(formOrder, z)
		check(g.length(z) == len(L)+len(R)+1, "m=%d: length of form %d", m, code)
		ds := g.desc(z)
		for _, j := range A {
			check(contains(ds, j) == (rm&(1<<uint(j-1)) != 0), "m=%d: descent %d of form %d", m, j, code)
		}
		if inInterval[z] {
			check(lm|rm == (uint64(1)<<uint(m))-1, "m=%d: interval element %d without full support", m, code)
		}
	}
	check(len(lowerOrder) == intPow(4, m)+intPow(2, m), "m=%d: |lower| = %d", m, len(lowerOrder))
	check(len(interval) == intPow(3, m)+1, "m=%d: |interval| = %d", m, len(interval))
	elig := g.eligible(w)
	if m >= 2 {
		check(len(elig) == 1 && elig[0] == x, "m=%d: eligible bottoms", m)
	} else {
		check(len(elig) == 0, "m=%d: eligible bottoms", m)
	}
	check(g.terminal(w) == (m >= 3), "m=%d: terminality", m)
	if allOrders {
		for _, z := range formOrder {
			f := forms[z]
			for _, z2 := range formOrder {
				f2 := forms[z2]
				want := f.L&^f2.L == 0 && f.R&^f2.R == 0
				check(g.leq(z, z2) == want, "m=%d: Bruhat order on forms", m)
			}
		}
	}
	for _, s := range g.desc(w) {
		check(equalPoly(g.withDescent(x, w, s), p), "m=%d: polynomial for descent %d differs from the reference polynomial", m, s)
	}
	ranks := map[int]int{}
	for _, z := range interval {
		ranks[g.length(z)-m]++
	}
	rv := make([]any, m+2)
	for i := range rv {
		rv[i] = ranks[i]
	}
	mu := int64(0)
	if m%2 == 0 {
		mu = p[m/2]
	}
	out := object{
		{"leaves", m},
		{"top_word", ints(topWord)},
		{"bottom_word", ints(A)},
		{"length_top", 2*m + 1},
		{"length_bottom", m},
		{"lower_size", len(lowerOrder)},
		{"interval_size", len(interval)},
		{"rank_vector", rv},
		{"polynomial", ints64(p)},
		{"mu", mu},
		{"terminal", g.terminal(w)},
		{"eligible_bottoms", len(elig)},
		{"all_pair_orders_checked", allOrders},
	}
	if !certificate {
		return out, nil
	}

	// Materialize all correction records before fixing the element-ID dictionary.
	snapshot := append([]pair(nil), g.klOrder...)
	for _, pr := range snapshot {
		if pr.a != pr.b && g.leq(pr.a, pr.b) {
			g.corrections(pr.b, g.desc(pr.b)[0])
		}
	}
	seen := map[int32]bool{}
	var elements []int32
	for _, z := range lowerOrder {
		seen[z] = true
		elements = append(elements, z)
	}
	for _, pr := range g.klOrder {
		for _, z := range []int32{pr.a, pr.b} {
			if !seen[z] {
				seen[z] = true
				elements = append(elements, z)
			}
		}
	}
	sort.Slice(elements, func(i, j int) bool {
		a, b := g.elems[elements[i]].m, g.elems[elements[j]].m
		for k := range a {
			if a[k] != b[k] {
				return a[k] < b[k]
			}
		}
		return false
	})
	indices := map[int32]int{}
	for i, z := range elements {
		indices[z] = i
	}
	terms := func(w int32, s int, bottom int32) []any {
		out := []any{}
		for _, c := range g.corrections(w, s) {
			if g.leq(bottom, c.z) {
				idx, ok := indices[c.z]
				check(ok, "correction element missing from the element table")
				out = append(out, []any{idx, c.d, c.mu})
			}
		}
		return out
	}
	// The records are emitted in first-computation order (g.klOrder), which
	// is a dependency order: every value a record's recurrence uses appears
	// earlier, so a consumer may replay the file sequentially.
	var records []any
	for _, pr := range g.klOrder {
		row := object{{"x", indices[pr.a]}, {"w", indices[pr.b]}, {"polynomial", ints64(g.klVals[pr])}}
		if pr.a != pr.b && g.leq(pr.a, pr.b) {
			s := g.desc(pr.b)[0]
			row = append(row, kv{"right_descent", s}, kv{"correction_terms", terms(pr.b, s, pr.a)})
		}
		records = append(records, row)
	}
	var elementRows []any
	for _, z := range elements {
		e := g.elems[z]
		cols := make([]any, g.n)
		for j := 0; j < g.n; j++ {
			col := make([]any, g.n)
			for i := 0; i < g.n; i++ {
				col[i] = int(e.m[j*g.n+i])
			}
			cols[j] = col
		}
		elementRows = append(elementRows, object{
			{"matrix", cols}, {"word", ints(g.word(z))}, {"length", g.length(z)}, {"R", ints(g.desc(z))},
		})
	}
	var top []any
	for _, s := range g.desc(w) {
		top = append(top, object{{"right_descent", s}, {"correction_terms", terms(w, s, x)}})
	}
	edges := make([]any, len(g.edges))
	for i, e := range g.edges {
		edges[i] = []any{e[0], e[1]}
	}
	data := object{
		{"format_version", 1},
		{"group", object{{"rank", m + 1}, {"edges", edges}}},
		{"convention", "Generator 0 is the center; generators 1,...,m are commuting leaves. Integral matrices are stored by columns. Polynomial coefficients ascend in q."},
		{"elements", elementRows},
		{"root", []any{indices[x], indices[w]}},
		{"records", records},
		{"top_recurrences", top},
		{"summary", out},
	}
	return out, append(encodeJSON(data, false), '\n')
}
